version: "3.8"

networks:
  crosstalk-dev:
    driver: bridge

services:
  server:
    build:
      context: ..
      dockerfile: dev/Dockerfile.server
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ../server:/app/server
      - ../proto:/app/proto
      - server-data:/data
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    ports:
      - "8080:8080"
    networks:
      - crosstalk-dev
    environment:
      - CROSSTALK_CONFIG=/app/server/dev.json

volumes:
  server-data:
  go-mod-cache:
  go-build-cache:
