// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/crosstalk/v2/control.proto

package crosstalkv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudioApplyState is the per-control apply/readback result.
type AudioApplyState int32

const (
	AudioApplyState_AUDIO_APPLY_STATE_UNSPECIFIED     AudioApplyState = 0
	AudioApplyState_AUDIO_APPLY_STATE_APPLIED         AudioApplyState = 1
	AudioApplyState_AUDIO_APPLY_STATE_UNSUPPORTED     AudioApplyState = 2
	AudioApplyState_AUDIO_APPLY_STATE_ERROR           AudioApplyState = 3
	AudioApplyState_AUDIO_APPLY_STATE_DEVICE_MISMATCH AudioApplyState = 4
	AudioApplyState_AUDIO_APPLY_STATE_STALE_REVISION  AudioApplyState = 5
)

// Enum value maps for AudioApplyState.
var (
	AudioApplyState_name = map[int32]string{
		0: "AUDIO_APPLY_STATE_UNSPECIFIED",
		1: "AUDIO_APPLY_STATE_APPLIED",
		2: "AUDIO_APPLY_STATE_UNSUPPORTED",
		3: "AUDIO_APPLY_STATE_ERROR",
		4: "AUDIO_APPLY_STATE_DEVICE_MISMATCH",
		5: "AUDIO_APPLY_STATE_STALE_REVISION",
	}
	AudioApplyState_value = map[string]int32{
		"AUDIO_APPLY_STATE_UNSPECIFIED":     0,
		"AUDIO_APPLY_STATE_APPLIED":         1,
		"AUDIO_APPLY_STATE_UNSUPPORTED":     2,
		"AUDIO_APPLY_STATE_ERROR":           3,
		"AUDIO_APPLY_STATE_DEVICE_MISMATCH": 4,
		"AUDIO_APPLY_STATE_STALE_REVISION":  5,
	}
)

func (x AudioApplyState) Enum() *AudioApplyState {
	p := new(AudioApplyState)
	*p = x
	return p
}

func (x AudioApplyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioApplyState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crosstalk_v2_control_proto_enumTypes[0].Descriptor()
}

func (AudioApplyState) Type() protoreflect.EnumType {
	return &file_proto_crosstalk_v2_control_proto_enumTypes[0]
}

func (x AudioApplyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioApplyState.Descriptor instead.
func (AudioApplyState) EnumDescriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{0}
}

// ControlMessage wraps all messages on the v3 WebRTC control data channel.
// Uses oneof for type-safe message dispatch.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Hello
	//	*ControlMessage_SourceStatus
	//	*ControlMessage_AudioControlReport
	//	*ControlMessage_Welcome
	//	*ControlMessage_MixUpdate
	//	*ControlMessage_Restart
	//	*ControlMessage_SessionAssignment
	//	*ControlMessage_AudioControlCommand
	//	*ControlMessage_LogEntry
	//	*ControlMessage_Ping
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControlMessage) GetSourceStatus() *SourceStatus {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_SourceStatus); ok {
			return x.SourceStatus
		}
	}
	return nil
}

func (x *ControlMessage) GetAudioControlReport() *AudioControlReport {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_AudioControlReport); ok {
			return x.AudioControlReport
		}
	}
	return nil
}

func (x *ControlMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ControlMessage) GetMixUpdate() *MixUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_MixUpdate); ok {
			return x.MixUpdate
		}
	}
	return nil
}

func (x *ControlMessage) GetRestart() *RestartCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *ControlMessage) GetSessionAssignment() *SessionAssignment {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_SessionAssignment); ok {
			return x.SessionAssignment
		}
	}
	return nil
}

func (x *ControlMessage) GetAudioControlCommand() *AudioControlCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_AudioControlCommand); ok {
			return x.AudioControlCommand
		}
	}
	return nil
}

func (x *ControlMessage) GetLogEntry() *LogEntry {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_LogEntry); ok {
			return x.LogEntry
		}
	}
	return nil
}

func (x *ControlMessage) GetPing() *PingPong {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Hello struct {
	// Client → Server
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ControlMessage_SourceStatus struct {
	SourceStatus *SourceStatus `protobuf:"bytes,2,opt,name=source_status,json=sourceStatus,proto3,oneof"`
}

type ControlMessage_AudioControlReport struct {
	AudioControlReport *AudioControlReport `protobuf:"bytes,3,opt,name=audio_control_report,json=audioControlReport,proto3,oneof"`
}

type ControlMessage_Welcome struct {
	// Server → Client
	Welcome *Welcome `protobuf:"bytes,10,opt,name=welcome,proto3,oneof"`
}

type ControlMessage_MixUpdate struct {
	MixUpdate *MixUpdate `protobuf:"bytes,11,opt,name=mix_update,json=mixUpdate,proto3,oneof"`
}

type ControlMessage_Restart struct {
	Restart *RestartCommand `protobuf:"bytes,12,opt,name=restart,proto3,oneof"`
}

type ControlMessage_SessionAssignment struct {
	SessionAssignment *SessionAssignment `protobuf:"bytes,13,opt,name=session_assignment,json=sessionAssignment,proto3,oneof"`
}

type ControlMessage_AudioControlCommand struct {
	AudioControlCommand *AudioControlCommand `protobuf:"bytes,14,opt,name=audio_control_command,json=audioControlCommand,proto3,oneof"`
}

type ControlMessage_LogEntry struct {
	// Bidirectional
	LogEntry *LogEntry `protobuf:"bytes,20,opt,name=log_entry,json=logEntry,proto3,oneof"`
}

type ControlMessage_Ping struct {
	Ping *PingPong `protobuf:"bytes,21,opt,name=ping,proto3,oneof"`
}

func (*ControlMessage_Hello) isControlMessage_Payload() {}

func (*ControlMessage_SourceStatus) isControlMessage_Payload() {}

func (*ControlMessage_AudioControlReport) isControlMessage_Payload() {}

func (*ControlMessage_Welcome) isControlMessage_Payload() {}

func (*ControlMessage_MixUpdate) isControlMessage_Payload() {}

func (*ControlMessage_Restart) isControlMessage_Payload() {}

func (*ControlMessage_SessionAssignment) isControlMessage_Payload() {}

func (*ControlMessage_AudioControlCommand) isControlMessage_Payload() {}

func (*ControlMessage_LogEntry) isControlMessage_Payload() {}

func (*ControlMessage_Ping) isControlMessage_Payload() {}

// Hello is sent by the client immediately after the control channel opens.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientType    string                 `protobuf:"bytes,1,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // "abc", "translator", "admin"
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Capabilities  []*AudioCapability     `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *Hello) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Hello) GetCapabilities() []*AudioCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// AudioCapability describes a client's audio codec support.
type AudioCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         string                 `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"` // e.g., "opus/48000/2"
	Channels      int32                  `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioCapability) Reset() {
	*x = AudioCapability{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioCapability) ProtoMessage() {}

func (x *AudioCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioCapability.ProtoReflect.Descriptor instead.
func (*AudioCapability) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{2}
}

func (x *AudioCapability) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *AudioCapability) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioCapability) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

// Welcome is sent by the server after receiving Hello.
type Welcome struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeerId            string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ServerVersion     string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	AssignedSessionId string                 `protobuf:"bytes,3,opt,name=assigned_session_id,json=assignedSessionId,proto3" json:"assigned_session_id,omitempty"` // pre-assigned for ABCs
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Welcome) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Welcome) GetAssignedSessionId() string {
	if x != nil {
		return x.AssignedSessionId
	}
	return ""
}

// MixUpdate tells the client about a change in the audio mix.
type MixUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Muted         bool                   `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
	Level         float32                `protobuf:"fixed32,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixUpdate) Reset() {
	*x = MixUpdate{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixUpdate) ProtoMessage() {}

func (x *MixUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixUpdate.ProtoReflect.Descriptor instead.
func (*MixUpdate) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{4}
}

func (x *MixUpdate) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MixUpdate) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *MixUpdate) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *MixUpdate) GetLevel() float32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// RestartCommand instructs the client to restart its connection.
type RestartCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartCommand) Reset() {
	*x = RestartCommand{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartCommand) ProtoMessage() {}

func (x *RestartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartCommand.ProtoReflect.Descriptor instead.
func (*RestartCommand) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{5}
}

func (x *RestartCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// SessionAssignment informs the client of its role in a session.
type SessionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // what this client is in the session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAssignment) Reset() {
	*x = SessionAssignment{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAssignment) ProtoMessage() {}

func (x *SessionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAssignment.ProtoReflect.Descriptor instead.
func (*SessionAssignment) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{6}
}

func (x *SessionAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionAssignment) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// SourceStatus reports the state of a client audio source.
type SourceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	PeakLevel     float32                `protobuf:"fixed32,3,opt,name=peak_level,json=peakLevel,proto3" json:"peak_level,omitempty"` // 0.0-1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStatus) Reset() {
	*x = SourceStatus{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatus) ProtoMessage() {}

func (x *SourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatus.ProtoReflect.Descriptor instead.
func (*SourceStatus) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{7}
}

func (x *SourceStatus) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *SourceStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *SourceStatus) GetPeakLevel() float32 {
	if x != nil {
		return x.PeakLevel
	}
	return 0
}

// LogEntry is a structured log message exchanged over the control channel.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// PingPong is used for latency measurement on the control channel.
type PingPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        int64                  `protobuf:"varint,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingPong) Reset() {
	*x = PingPong{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPong) ProtoMessage() {}

func (x *PingPong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPong.ProtoReflect.Descriptor instead.
func (*PingPong) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{9}
}

func (x *PingPong) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

// AudioControlCommand is an absolute desired USB mixer state (server → client).
// Field numbers are fixed; do not renumber.
type AudioControlCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DesiredRevision uint64                 `protobuf:"varint,2,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	Output          *AudioOutputDesired    `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Input           *AudioInputDesired     `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioControlCommand) Reset() {
	*x = AudioControlCommand{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioControlCommand) ProtoMessage() {}

func (x *AudioControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioControlCommand.ProtoReflect.Descriptor instead.
func (*AudioControlCommand) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{10}
}

func (x *AudioControlCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AudioControlCommand) GetDesiredRevision() uint64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *AudioControlCommand) GetOutput() *AudioOutputDesired {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *AudioControlCommand) GetInput() *AudioInputDesired {
	if x != nil {
		return x.Input
	}
	return nil
}

// AudioOutputDesired is the absolute desired playback mixer state.
type AudioOutputDesired struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	// Presence distinguishes 0% from unset. Range when set: inclusive 0..100.
	VolumePercent *uint32 `protobuf:"varint,2,opt,name=volume_percent,json=volumePercent,proto3,oneof" json:"volume_percent,omitempty"`
	Muted         *bool   `protobuf:"varint,3,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioOutputDesired) Reset() {
	*x = AudioOutputDesired{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioOutputDesired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioOutputDesired) ProtoMessage() {}

func (x *AudioOutputDesired) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioOutputDesired.ProtoReflect.Descriptor instead.
func (*AudioOutputDesired) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{11}
}

func (x *AudioOutputDesired) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *AudioOutputDesired) GetVolumePercent() uint32 {
	if x != nil && x.VolumePercent != nil {
		return *x.VolumePercent
	}
	return 0
}

func (x *AudioOutputDesired) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

// AudioInputDesired is the absolute desired capture mixer state.
type AudioInputDesired struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	// Presence distinguishes 0% from unset. Range when set: inclusive 0..100.
	GainPercent   *uint32 `protobuf:"varint,2,opt,name=gain_percent,json=gainPercent,proto3,oneof" json:"gain_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioInputDesired) Reset() {
	*x = AudioInputDesired{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioInputDesired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioInputDesired) ProtoMessage() {}

func (x *AudioInputDesired) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioInputDesired.ProtoReflect.Descriptor instead.
func (*AudioInputDesired) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{12}
}

func (x *AudioInputDesired) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *AudioInputDesired) GetGainPercent() uint32 {
	if x != nil && x.GainPercent != nil {
		return *x.GainPercent
	}
	return 0
}

// AudioControlReport is inventory and/or apply result (client → server).
// desired_revision 0 is inventory-only.
type AudioControlReport struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	CommandId       string                   `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DesiredRevision uint64                   `protobuf:"varint,2,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	Devices         []*AudioDeviceCapability `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	Output          *AudioOutputObserved     `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Input           *AudioInputObserved      `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	ErrorCode       string                   `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDetail     string                   `protobuf:"bytes,7,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioControlReport) Reset() {
	*x = AudioControlReport{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioControlReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioControlReport) ProtoMessage() {}

func (x *AudioControlReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioControlReport.ProtoReflect.Descriptor instead.
func (*AudioControlReport) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{13}
}

func (x *AudioControlReport) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AudioControlReport) GetDesiredRevision() uint64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *AudioControlReport) GetDevices() []*AudioDeviceCapability {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *AudioControlReport) GetOutput() *AudioOutputObserved {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *AudioControlReport) GetInput() *AudioInputObserved {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *AudioControlReport) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AudioControlReport) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

// AudioDeviceCapability describes one discovered audio endpoint.
type AudioDeviceCapability struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid          string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	Direction          string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"` // "input", "output", or "both"
	Backend            string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`     // "alsa", "pipewire", ...
	VendorId           string                 `protobuf:"bytes,4,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ProductId          string                 `protobuf:"bytes,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Serial             string                 `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`
	Path               string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	AlsaCardId         string                 `protobuf:"bytes,8,opt,name=alsa_card_id,json=alsaCardId,proto3" json:"alsa_card_id,omitempty"`
	CardName           string                 `protobuf:"bytes,9,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	PcmRoute           string                 `protobuf:"bytes,10,opt,name=pcm_route,json=pcmRoute,proto3" json:"pcm_route,omitempty"`
	SupportsVolume     bool                   `protobuf:"varint,11,opt,name=supports_volume,json=supportsVolume,proto3" json:"supports_volume,omitempty"`
	SupportsMute       bool                   `protobuf:"varint,12,opt,name=supports_mute,json=supportsMute,proto3" json:"supports_mute,omitempty"`
	SupportsGain       bool                   `protobuf:"varint,13,opt,name=supports_gain,json=supportsGain,proto3" json:"supports_gain,omitempty"`
	SupportsAgcDisable bool                   `protobuf:"varint,14,opt,name=supports_agc_disable,json=supportsAgcDisable,proto3" json:"supports_agc_disable,omitempty"`
	// Optional dB/range metadata when known from amixer.
	VolumeMinDb   *int32 `protobuf:"varint,15,opt,name=volume_min_db,json=volumeMinDb,proto3,oneof" json:"volume_min_db,omitempty"`
	VolumeMaxDb   *int32 `protobuf:"varint,16,opt,name=volume_max_db,json=volumeMaxDb,proto3,oneof" json:"volume_max_db,omitempty"`
	VolumeStepDb  *int32 `protobuf:"varint,17,opt,name=volume_step_db,json=volumeStepDb,proto3,oneof" json:"volume_step_db,omitempty"`
	GainMinDb     *int32 `protobuf:"varint,18,opt,name=gain_min_db,json=gainMinDb,proto3,oneof" json:"gain_min_db,omitempty"`
	GainMaxDb     *int32 `protobuf:"varint,19,opt,name=gain_max_db,json=gainMaxDb,proto3,oneof" json:"gain_max_db,omitempty"`
	GainStepDb    *int32 `protobuf:"varint,20,opt,name=gain_step_db,json=gainStepDb,proto3,oneof" json:"gain_step_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDeviceCapability) Reset() {
	*x = AudioDeviceCapability{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDeviceCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDeviceCapability) ProtoMessage() {}

func (x *AudioDeviceCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDeviceCapability.ProtoReflect.Descriptor instead.
func (*AudioDeviceCapability) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{14}
}

func (x *AudioDeviceCapability) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *AudioDeviceCapability) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *AudioDeviceCapability) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *AudioDeviceCapability) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *AudioDeviceCapability) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AudioDeviceCapability) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *AudioDeviceCapability) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AudioDeviceCapability) GetAlsaCardId() string {
	if x != nil {
		return x.AlsaCardId
	}
	return ""
}

func (x *AudioDeviceCapability) GetCardName() string {
	if x != nil {
		return x.CardName
	}
	return ""
}

func (x *AudioDeviceCapability) GetPcmRoute() string {
	if x != nil {
		return x.PcmRoute
	}
	return ""
}

func (x *AudioDeviceCapability) GetSupportsVolume() bool {
	if x != nil {
		return x.SupportsVolume
	}
	return false
}

func (x *AudioDeviceCapability) GetSupportsMute() bool {
	if x != nil {
		return x.SupportsMute
	}
	return false
}

func (x *AudioDeviceCapability) GetSupportsGain() bool {
	if x != nil {
		return x.SupportsGain
	}
	return false
}

func (x *AudioDeviceCapability) GetSupportsAgcDisable() bool {
	if x != nil {
		return x.SupportsAgcDisable
	}
	return false
}

func (x *AudioDeviceCapability) GetVolumeMinDb() int32 {
	if x != nil && x.VolumeMinDb != nil {
		return *x.VolumeMinDb
	}
	return 0
}

func (x *AudioDeviceCapability) GetVolumeMaxDb() int32 {
	if x != nil && x.VolumeMaxDb != nil {
		return *x.VolumeMaxDb
	}
	return 0
}

func (x *AudioDeviceCapability) GetVolumeStepDb() int32 {
	if x != nil && x.VolumeStepDb != nil {
		return *x.VolumeStepDb
	}
	return 0
}

func (x *AudioDeviceCapability) GetGainMinDb() int32 {
	if x != nil && x.GainMinDb != nil {
		return *x.GainMinDb
	}
	return 0
}

func (x *AudioDeviceCapability) GetGainMaxDb() int32 {
	if x != nil && x.GainMaxDb != nil {
		return *x.GainMaxDb
	}
	return 0
}

func (x *AudioDeviceCapability) GetGainStepDb() int32 {
	if x != nil && x.GainStepDb != nil {
		return *x.GainStepDb
	}
	return 0
}

// AudioOutputObserved is the effective playback mixer readback.
type AudioOutputObserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid     string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	VolumePercent *uint32                `protobuf:"varint,2,opt,name=volume_percent,json=volumePercent,proto3,oneof" json:"volume_percent,omitempty"`
	Muted         *bool                  `protobuf:"varint,3,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	VolumeState   AudioApplyState        `protobuf:"varint,4,opt,name=volume_state,json=volumeState,proto3,enum=crosstalk.v2.AudioApplyState" json:"volume_state,omitempty"`
	MuteState     AudioApplyState        `protobuf:"varint,5,opt,name=mute_state,json=muteState,proto3,enum=crosstalk.v2.AudioApplyState" json:"mute_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioOutputObserved) Reset() {
	*x = AudioOutputObserved{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioOutputObserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioOutputObserved) ProtoMessage() {}

func (x *AudioOutputObserved) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioOutputObserved.ProtoReflect.Descriptor instead.
func (*AudioOutputObserved) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{15}
}

func (x *AudioOutputObserved) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *AudioOutputObserved) GetVolumePercent() uint32 {
	if x != nil && x.VolumePercent != nil {
		return *x.VolumePercent
	}
	return 0
}

func (x *AudioOutputObserved) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

func (x *AudioOutputObserved) GetVolumeState() AudioApplyState {
	if x != nil {
		return x.VolumeState
	}
	return AudioApplyState_AUDIO_APPLY_STATE_UNSPECIFIED
}

func (x *AudioOutputObserved) GetMuteState() AudioApplyState {
	if x != nil {
		return x.MuteState
	}
	return AudioApplyState_AUDIO_APPLY_STATE_UNSPECIFIED
}

// AudioInputObserved is the effective capture mixer readback.
type AudioInputObserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid     string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	GainPercent   *uint32                `protobuf:"varint,2,opt,name=gain_percent,json=gainPercent,proto3,oneof" json:"gain_percent,omitempty"`
	GainState     AudioApplyState        `protobuf:"varint,3,opt,name=gain_state,json=gainState,proto3,enum=crosstalk.v2.AudioApplyState" json:"gain_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioInputObserved) Reset() {
	*x = AudioInputObserved{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioInputObserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioInputObserved) ProtoMessage() {}

func (x *AudioInputObserved) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioInputObserved.ProtoReflect.Descriptor instead.
func (*AudioInputObserved) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{16}
}

func (x *AudioInputObserved) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *AudioInputObserved) GetGainPercent() uint32 {
	if x != nil && x.GainPercent != nil {
		return *x.GainPercent
	}
	return 0
}

func (x *AudioInputObserved) GetGainState() AudioApplyState {
	if x != nil {
		return x.GainState
	}
	return AudioApplyState_AUDIO_APPLY_STATE_UNSPECIFIED
}

var File_proto_crosstalk_v2_control_proto protoreflect.FileDescriptor

const file_proto_crosstalk_v2_control_proto_rawDesc = "" +
	"\n" +
	" proto/crosstalk/v2/control.proto\x12\fcrosstalk.v2\"\x98\x05\n" +
	"\x0eControlMessage\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.crosstalk.v2.HelloH\x00R\x05hello\x12A\n" +
	"\rsource_status\x18\x02 \x01(\v2\x1a.crosstalk.v2.SourceStatusH\x00R\fsourceStatus\x12T\n" +
	"\x14audio_control_report\x18\x03 \x01(\v2 .crosstalk.v2.AudioControlReportH\x00R\x12audioControlReport\x121\n" +
	"\awelcome\x18\n" +
	" \x01(\v2\x15.crosstalk.v2.WelcomeH\x00R\awelcome\x128\n" +
	"\n" +
	"mix_update\x18\v \x01(\v2\x17.crosstalk.v2.MixUpdateH\x00R\tmixUpdate\x128\n" +
	"\arestart\x18\f \x01(\v2\x1c.crosstalk.v2.RestartCommandH\x00R\arestart\x12P\n" +
	"\x12session_assignment\x18\r \x01(\v2\x1f.crosstalk.v2.SessionAssignmentH\x00R\x11sessionAssignment\x12W\n" +
	"\x15audio_control_command\x18\x0e \x01(\v2!.crosstalk.v2.AudioControlCommandH\x00R\x13audioControlCommand\x125\n" +
	"\tlog_entry\x18\x14 \x01(\v2\x16.crosstalk.v2.LogEntryH\x00R\blogEntry\x12,\n" +
	"\x04ping\x18\x15 \x01(\v2\x16.crosstalk.v2.PingPongH\x00R\x04pingB\t\n" +
	"\apayload\"\x8c\x01\n" +
	"\x05Hello\x12\x1f\n" +
	"\vclient_type\x18\x01 \x01(\tR\n" +
	"clientType\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12A\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1d.crosstalk.v2.AudioCapabilityR\fcapabilities\"d\n" +
	"\x0fAudioCapability\x12\x14\n" +
	"\x05codec\x18\x01 \x01(\tR\x05codec\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\x05R\bchannels\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\"y\n" +
	"\aWelcome\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12.\n" +
	"\x13assigned_session_id\x18\x03 \x01(\tR\x11assignedSessionId\"s\n" +
	"\tMixUpdate\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05muted\x18\x03 \x01(\bR\x05muted\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x02R\x05level\"(\n" +
	"\x0eRestartCommand\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"F\n" +
	"\x11SessionAssignment\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"f\n" +
	"\fSourceStatus\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"peak_level\x18\x03 \x01(\x02R\tpeakLevel\"\xed\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12:\n" +
	"\x06fields\x18\x05 \x03(\v2\".crosstalk.v2.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\bPingPong\x12\x17\n" +
	"\asent_at\x18\x01 \x01(\x03R\x06sentAt\"\xd0\x01\n" +
	"\x13AudioControlCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12)\n" +
	"\x10desired_revision\x18\x02 \x01(\x04R\x0fdesiredRevision\x128\n" +
	"\x06output\x18\x03 \x01(\v2 .crosstalk.v2.AudioOutputDesiredR\x06output\x125\n" +
	"\x05input\x18\x04 \x01(\v2\x1f.crosstalk.v2.AudioInputDesiredR\x05input\"\x97\x01\n" +
	"\x12AudioOutputDesired\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12*\n" +
	"\x0evolume_percent\x18\x02 \x01(\rH\x00R\rvolumePercent\x88\x01\x01\x12\x19\n" +
	"\x05muted\x18\x03 \x01(\bH\x01R\x05muted\x88\x01\x01B\x11\n" +
	"\x0f_volume_percentB\b\n" +
	"\x06_muted\"k\n" +
	"\x11AudioInputDesired\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12&\n" +
	"\fgain_percent\x18\x02 \x01(\rH\x00R\vgainPercent\x88\x01\x01B\x0f\n" +
	"\r_gain_percent\"\xd2\x02\n" +
	"\x12AudioControlReport\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12)\n" +
	"\x10desired_revision\x18\x02 \x01(\x04R\x0fdesiredRevision\x12=\n" +
	"\adevices\x18\x03 \x03(\v2#.crosstalk.v2.AudioDeviceCapabilityR\adevices\x129\n" +
	"\x06output\x18\x04 \x01(\v2!.crosstalk.v2.AudioOutputObservedR\x06output\x126\n" +
	"\x05input\x18\x05 \x01(\v2 .crosstalk.v2.AudioInputObservedR\x05input\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12!\n" +
	"\ferror_detail\x18\a \x01(\tR\verrorDetail\"\xad\x06\n" +
	"\x15AudioDeviceCapability\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x1b\n" +
	"\tvendor_id\x18\x04 \x01(\tR\bvendorId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\tR\tproductId\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\tR\x06serial\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12 \n" +
	"\falsa_card_id\x18\b \x01(\tR\n" +
	"alsaCardId\x12\x1b\n" +
	"\tcard_name\x18\t \x01(\tR\bcardName\x12\x1b\n" +
	"\tpcm_route\x18\n" +
	" \x01(\tR\bpcmRoute\x12'\n" +
	"\x0fsupports_volume\x18\v \x01(\bR\x0esupportsVolume\x12#\n" +
	"\rsupports_mute\x18\f \x01(\bR\fsupportsMute\x12#\n" +
	"\rsupports_gain\x18\r \x01(\bR\fsupportsGain\x120\n" +
	"\x14supports_agc_disable\x18\x0e \x01(\bR\x12supportsAgcDisable\x12'\n" +
	"\rvolume_min_db\x18\x0f \x01(\x05H\x00R\vvolumeMinDb\x88\x01\x01\x12'\n" +
	"\rvolume_max_db\x18\x10 \x01(\x05H\x01R\vvolumeMaxDb\x88\x01\x01\x12)\n" +
	"\x0evolume_step_db\x18\x11 \x01(\x05H\x02R\fvolumeStepDb\x88\x01\x01\x12#\n" +
	"\vgain_min_db\x18\x12 \x01(\x05H\x03R\tgainMinDb\x88\x01\x01\x12#\n" +
	"\vgain_max_db\x18\x13 \x01(\x05H\x04R\tgainMaxDb\x88\x01\x01\x12%\n" +
	"\fgain_step_db\x18\x14 \x01(\x05H\x05R\n" +
	"gainStepDb\x88\x01\x01B\x10\n" +
	"\x0e_volume_min_dbB\x10\n" +
	"\x0e_volume_max_dbB\x11\n" +
	"\x0f_volume_step_dbB\x0e\n" +
	"\f_gain_min_dbB\x0e\n" +
	"\f_gain_max_dbB\x0f\n" +
	"\r_gain_step_db\"\x98\x02\n" +
	"\x13AudioOutputObserved\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12*\n" +
	"\x0evolume_percent\x18\x02 \x01(\rH\x00R\rvolumePercent\x88\x01\x01\x12\x19\n" +
	"\x05muted\x18\x03 \x01(\bH\x01R\x05muted\x88\x01\x01\x12@\n" +
	"\fvolume_state\x18\x04 \x01(\x0e2\x1d.crosstalk.v2.AudioApplyStateR\vvolumeState\x12<\n" +
	"\n" +
	"mute_state\x18\x05 \x01(\x0e2\x1d.crosstalk.v2.AudioApplyStateR\tmuteStateB\x11\n" +
	"\x0f_volume_percentB\b\n" +
	"\x06_muted\"\xaa\x01\n" +
	"\x12AudioInputObserved\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12&\n" +
	"\fgain_percent\x18\x02 \x01(\rH\x00R\vgainPercent\x88\x01\x01\x12<\n" +
	"\n" +
	"gain_state\x18\x03 \x01(\x0e2\x1d.crosstalk.v2.AudioApplyStateR\tgainStateB\x0f\n" +
	"\r_gain_percent*\xe0\x01\n" +
	"\x0fAudioApplyState\x12!\n" +
	"\x1dAUDIO_APPLY_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19AUDIO_APPLY_STATE_APPLIED\x10\x01\x12!\n" +
	"\x1dAUDIO_APPLY_STATE_UNSUPPORTED\x10\x02\x12\x1b\n" +
	"\x17AUDIO_APPLY_STATE_ERROR\x10\x03\x12%\n" +
	"!AUDIO_APPLY_STATE_DEVICE_MISMATCH\x10\x04\x12$\n" +
	" AUDIO_APPLY_STATE_STALE_REVISION\x10\x05BGZEgithub.com/aleksclark/crosstalk/proto/gen/go/crosstalk/v2;crosstalkv2b\x06proto3"

var (
	file_proto_crosstalk_v2_control_proto_rawDescOnce sync.Once
	file_proto_crosstalk_v2_control_proto_rawDescData []byte
)

func file_proto_crosstalk_v2_control_proto_rawDescGZIP() []byte {
	file_proto_crosstalk_v2_control_proto_rawDescOnce.Do(func() {
		file_proto_crosstalk_v2_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crosstalk_v2_control_proto_rawDesc), len(file_proto_crosstalk_v2_control_proto_rawDesc)))
	})
	return file_proto_crosstalk_v2_control_proto_rawDescData
}

var file_proto_crosstalk_v2_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_crosstalk_v2_control_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_crosstalk_v2_control_proto_goTypes = []any{
	(AudioApplyState)(0),          // 0: crosstalk.v2.AudioApplyState
	(*ControlMessage)(nil),        // 1: crosstalk.v2.ControlMessage
	(*Hello)(nil),                 // 2: crosstalk.v2.Hello
	(*AudioCapability)(nil),       // 3: crosstalk.v2.AudioCapability
	(*Welcome)(nil),               // 4: crosstalk.v2.Welcome
	(*MixUpdate)(nil),             // 5: crosstalk.v2.MixUpdate
	(*RestartCommand)(nil),        // 6: crosstalk.v2.RestartCommand
	(*SessionAssignment)(nil),     // 7: crosstalk.v2.SessionAssignment
	(*SourceStatus)(nil),          // 8: crosstalk.v2.SourceStatus
	(*LogEntry)(nil),              // 9: crosstalk.v2.LogEntry
	(*PingPong)(nil),              // 10: crosstalk.v2.PingPong
	(*AudioControlCommand)(nil),   // 11: crosstalk.v2.AudioControlCommand
	(*AudioOutputDesired)(nil),    // 12: crosstalk.v2.AudioOutputDesired
	(*AudioInputDesired)(nil),     // 13: crosstalk.v2.AudioInputDesired
	(*AudioControlReport)(nil),    // 14: crosstalk.v2.AudioControlReport
	(*AudioDeviceCapability)(nil), // 15: crosstalk.v2.AudioDeviceCapability
	(*AudioOutputObserved)(nil),   // 16: crosstalk.v2.AudioOutputObserved
	(*AudioInputObserved)(nil),    // 17: crosstalk.v2.AudioInputObserved
	nil,                           // 18: crosstalk.v2.LogEntry.FieldsEntry
}
var file_proto_crosstalk_v2_control_proto_depIdxs = []int32{
	2,  // 0: crosstalk.v2.ControlMessage.hello:type_name -> crosstalk.v2.Hello
	8,  // 1: crosstalk.v2.ControlMessage.source_status:type_name -> crosstalk.v2.SourceStatus
	14, // 2: crosstalk.v2.ControlMessage.audio_control_report:type_name -> crosstalk.v2.AudioControlReport
	4,  // 3: crosstalk.v2.ControlMessage.welcome:type_name -> crosstalk.v2.Welcome
	5,  // 4: crosstalk.v2.ControlMessage.mix_update:type_name -> crosstalk.v2.MixUpdate
	6,  // 5: crosstalk.v2.ControlMessage.restart:type_name -> crosstalk.v2.RestartCommand
	7,  // 6: crosstalk.v2.ControlMessage.session_assignment:type_name -> crosstalk.v2.SessionAssignment
	11, // 7: crosstalk.v2.ControlMessage.audio_control_command:type_name -> crosstalk.v2.AudioControlCommand
	9,  // 8: crosstalk.v2.ControlMessage.log_entry:type_name -> crosstalk.v2.LogEntry
	10, // 9: crosstalk.v2.ControlMessage.ping:type_name -> crosstalk.v2.PingPong
	3,  // 10: crosstalk.v2.Hello.capabilities:type_name -> crosstalk.v2.AudioCapability
	18, // 11: crosstalk.v2.LogEntry.fields:type_name -> crosstalk.v2.LogEntry.FieldsEntry
	12, // 12: crosstalk.v2.AudioControlCommand.output:type_name -> crosstalk.v2.AudioOutputDesired
	13, // 13: crosstalk.v2.AudioControlCommand.input:type_name -> crosstalk.v2.AudioInputDesired
	15, // 14: crosstalk.v2.AudioControlReport.devices:type_name -> crosstalk.v2.AudioDeviceCapability
	16, // 15: crosstalk.v2.AudioControlReport.output:type_name -> crosstalk.v2.AudioOutputObserved
	17, // 16: crosstalk.v2.AudioControlReport.input:type_name -> crosstalk.v2.AudioInputObserved
	0,  // 17: crosstalk.v2.AudioOutputObserved.volume_state:type_name -> crosstalk.v2.AudioApplyState
	0,  // 18: crosstalk.v2.AudioOutputObserved.mute_state:type_name -> crosstalk.v2.AudioApplyState
	0,  // 19: crosstalk.v2.AudioInputObserved.gain_state:type_name -> crosstalk.v2.AudioApplyState
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_crosstalk_v2_control_proto_init() }
func file_proto_crosstalk_v2_control_proto_init() {
	if File_proto_crosstalk_v2_control_proto != nil {
		return
	}
	file_proto_crosstalk_v2_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_Hello)(nil),
		(*ControlMessage_SourceStatus)(nil),
		(*ControlMessage_AudioControlReport)(nil),
		(*ControlMessage_Welcome)(nil),
		(*ControlMessage_MixUpdate)(nil),
		(*ControlMessage_Restart)(nil),
		(*ControlMessage_SessionAssignment)(nil),
		(*ControlMessage_AudioControlCommand)(nil),
		(*ControlMessage_LogEntry)(nil),
		(*ControlMessage_Ping)(nil),
	}
	file_proto_crosstalk_v2_control_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_crosstalk_v2_control_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_crosstalk_v2_control_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_crosstalk_v2_control_proto_msgTypes[15].OneofWrappers = []any{}
	file_proto_crosstalk_v2_control_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crosstalk_v2_control_proto_rawDesc), len(file_proto_crosstalk_v2_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_crosstalk_v2_control_proto_goTypes,
		DependencyIndexes: file_proto_crosstalk_v2_control_proto_depIdxs,
		EnumInfos:         file_proto_crosstalk_v2_control_proto_enumTypes,
		MessageInfos:      file_proto_crosstalk_v2_control_proto_msgTypes,
	}.Build()
	File_proto_crosstalk_v2_control_proto = out.File
	file_proto_crosstalk_v2_control_proto_goTypes = nil
	file_proto_crosstalk_v2_control_proto_depIdxs = nil
}
