// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/crosstalk/v2/control.proto

package crosstalkv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlMessage wraps all messages on the v3 WebRTC control data channel.
// Uses oneof for type-safe message dispatch.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Hello
	//	*ControlMessage_SourceStatus
	//	*ControlMessage_Welcome
	//	*ControlMessage_MixUpdate
	//	*ControlMessage_Restart
	//	*ControlMessage_SessionAssignment
	//	*ControlMessage_LogEntry
	//	*ControlMessage_Ping
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControlMessage) GetSourceStatus() *SourceStatus {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_SourceStatus); ok {
			return x.SourceStatus
		}
	}
	return nil
}

func (x *ControlMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ControlMessage) GetMixUpdate() *MixUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_MixUpdate); ok {
			return x.MixUpdate
		}
	}
	return nil
}

func (x *ControlMessage) GetRestart() *RestartCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *ControlMessage) GetSessionAssignment() *SessionAssignment {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_SessionAssignment); ok {
			return x.SessionAssignment
		}
	}
	return nil
}

func (x *ControlMessage) GetLogEntry() *LogEntry {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_LogEntry); ok {
			return x.LogEntry
		}
	}
	return nil
}

func (x *ControlMessage) GetPing() *PingPong {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Hello struct {
	// Client → Server
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ControlMessage_SourceStatus struct {
	SourceStatus *SourceStatus `protobuf:"bytes,2,opt,name=source_status,json=sourceStatus,proto3,oneof"`
}

type ControlMessage_Welcome struct {
	// Server → Client
	Welcome *Welcome `protobuf:"bytes,10,opt,name=welcome,proto3,oneof"`
}

type ControlMessage_MixUpdate struct {
	MixUpdate *MixUpdate `protobuf:"bytes,11,opt,name=mix_update,json=mixUpdate,proto3,oneof"`
}

type ControlMessage_Restart struct {
	Restart *RestartCommand `protobuf:"bytes,12,opt,name=restart,proto3,oneof"`
}

type ControlMessage_SessionAssignment struct {
	SessionAssignment *SessionAssignment `protobuf:"bytes,13,opt,name=session_assignment,json=sessionAssignment,proto3,oneof"`
}

type ControlMessage_LogEntry struct {
	// Bidirectional
	LogEntry *LogEntry `protobuf:"bytes,20,opt,name=log_entry,json=logEntry,proto3,oneof"`
}

type ControlMessage_Ping struct {
	Ping *PingPong `protobuf:"bytes,21,opt,name=ping,proto3,oneof"`
}

func (*ControlMessage_Hello) isControlMessage_Payload() {}

func (*ControlMessage_SourceStatus) isControlMessage_Payload() {}

func (*ControlMessage_Welcome) isControlMessage_Payload() {}

func (*ControlMessage_MixUpdate) isControlMessage_Payload() {}

func (*ControlMessage_Restart) isControlMessage_Payload() {}

func (*ControlMessage_SessionAssignment) isControlMessage_Payload() {}

func (*ControlMessage_LogEntry) isControlMessage_Payload() {}

func (*ControlMessage_Ping) isControlMessage_Payload() {}

// Hello is sent by the client immediately after the control channel opens.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientType    string                 `protobuf:"bytes,1,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // "abc", "translator", "admin"
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Capabilities  []*AudioCapability     `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *Hello) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Hello) GetCapabilities() []*AudioCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// AudioCapability describes a client's audio codec support.
type AudioCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         string                 `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"` // e.g., "opus/48000/2"
	Channels      int32                  `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioCapability) Reset() {
	*x = AudioCapability{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioCapability) ProtoMessage() {}

func (x *AudioCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioCapability.ProtoReflect.Descriptor instead.
func (*AudioCapability) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{2}
}

func (x *AudioCapability) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *AudioCapability) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioCapability) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

// Welcome is sent by the server after receiving Hello.
type Welcome struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeerId            string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ServerVersion     string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	AssignedSessionId string                 `protobuf:"bytes,3,opt,name=assigned_session_id,json=assignedSessionId,proto3" json:"assigned_session_id,omitempty"` // pre-assigned for ABCs
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Welcome) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Welcome) GetAssignedSessionId() string {
	if x != nil {
		return x.AssignedSessionId
	}
	return ""
}

// MixUpdate tells the client about a change in the audio mix.
type MixUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Muted         bool                   `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
	Level         float32                `protobuf:"fixed32,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixUpdate) Reset() {
	*x = MixUpdate{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixUpdate) ProtoMessage() {}

func (x *MixUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixUpdate.ProtoReflect.Descriptor instead.
func (*MixUpdate) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{4}
}

func (x *MixUpdate) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MixUpdate) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *MixUpdate) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *MixUpdate) GetLevel() float32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// RestartCommand instructs the client to restart its connection.
type RestartCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartCommand) Reset() {
	*x = RestartCommand{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartCommand) ProtoMessage() {}

func (x *RestartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartCommand.ProtoReflect.Descriptor instead.
func (*RestartCommand) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{5}
}

func (x *RestartCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// SessionAssignment informs the client of its role in a session.
type SessionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // what this client is in the session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAssignment) Reset() {
	*x = SessionAssignment{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAssignment) ProtoMessage() {}

func (x *SessionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAssignment.ProtoReflect.Descriptor instead.
func (*SessionAssignment) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{6}
}

func (x *SessionAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionAssignment) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// SourceStatus reports the state of a client audio source.
type SourceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	PeakLevel     float32                `protobuf:"fixed32,3,opt,name=peak_level,json=peakLevel,proto3" json:"peak_level,omitempty"` // 0.0-1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStatus) Reset() {
	*x = SourceStatus{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatus) ProtoMessage() {}

func (x *SourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatus.ProtoReflect.Descriptor instead.
func (*SourceStatus) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{7}
}

func (x *SourceStatus) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *SourceStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *SourceStatus) GetPeakLevel() float32 {
	if x != nil {
		return x.PeakLevel
	}
	return 0
}

// LogEntry is a structured log message exchanged over the control channel.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// PingPong is used for latency measurement on the control channel.
type PingPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        int64                  `protobuf:"varint,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingPong) Reset() {
	*x = PingPong{}
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPong) ProtoMessage() {}

func (x *PingPong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosstalk_v2_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPong.ProtoReflect.Descriptor instead.
func (*PingPong) Descriptor() ([]byte, []int) {
	return file_proto_crosstalk_v2_control_proto_rawDescGZIP(), []int{9}
}

func (x *PingPong) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

var File_proto_crosstalk_v2_control_proto protoreflect.FileDescriptor

const file_proto_crosstalk_v2_control_proto_rawDesc = "" +
	"\n" +
	" proto/crosstalk/v2/control.proto\x12\fcrosstalk.v2\"\xe9\x03\n" +
	"\x0eControlMessage\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.crosstalk.v2.HelloH\x00R\x05hello\x12A\n" +
	"\rsource_status\x18\x02 \x01(\v2\x1a.crosstalk.v2.SourceStatusH\x00R\fsourceStatus\x121\n" +
	"\awelcome\x18\n" +
	" \x01(\v2\x15.crosstalk.v2.WelcomeH\x00R\awelcome\x128\n" +
	"\n" +
	"mix_update\x18\v \x01(\v2\x17.crosstalk.v2.MixUpdateH\x00R\tmixUpdate\x128\n" +
	"\arestart\x18\f \x01(\v2\x1c.crosstalk.v2.RestartCommandH\x00R\arestart\x12P\n" +
	"\x12session_assignment\x18\r \x01(\v2\x1f.crosstalk.v2.SessionAssignmentH\x00R\x11sessionAssignment\x125\n" +
	"\tlog_entry\x18\x14 \x01(\v2\x16.crosstalk.v2.LogEntryH\x00R\blogEntry\x12,\n" +
	"\x04ping\x18\x15 \x01(\v2\x16.crosstalk.v2.PingPongH\x00R\x04pingB\t\n" +
	"\apayload\"\x8c\x01\n" +
	"\x05Hello\x12\x1f\n" +
	"\vclient_type\x18\x01 \x01(\tR\n" +
	"clientType\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12A\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1d.crosstalk.v2.AudioCapabilityR\fcapabilities\"d\n" +
	"\x0fAudioCapability\x12\x14\n" +
	"\x05codec\x18\x01 \x01(\tR\x05codec\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\x05R\bchannels\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\"y\n" +
	"\aWelcome\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12.\n" +
	"\x13assigned_session_id\x18\x03 \x01(\tR\x11assignedSessionId\"s\n" +
	"\tMixUpdate\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05muted\x18\x03 \x01(\bR\x05muted\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x02R\x05level\"(\n" +
	"\x0eRestartCommand\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"F\n" +
	"\x11SessionAssignment\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"f\n" +
	"\fSourceStatus\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"peak_level\x18\x03 \x01(\x02R\tpeakLevel\"\xed\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12:\n" +
	"\x06fields\x18\x05 \x03(\v2\".crosstalk.v2.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\bPingPong\x12\x17\n" +
	"\asent_at\x18\x01 \x01(\x03R\x06sentAtBGZEgithub.com/aleksclark/crosstalk/proto/gen/go/crosstalk/v2;crosstalkv2b\x06proto3"

var (
	file_proto_crosstalk_v2_control_proto_rawDescOnce sync.Once
	file_proto_crosstalk_v2_control_proto_rawDescData []byte
)

func file_proto_crosstalk_v2_control_proto_rawDescGZIP() []byte {
	file_proto_crosstalk_v2_control_proto_rawDescOnce.Do(func() {
		file_proto_crosstalk_v2_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crosstalk_v2_control_proto_rawDesc), len(file_proto_crosstalk_v2_control_proto_rawDesc)))
	})
	return file_proto_crosstalk_v2_control_proto_rawDescData
}

var file_proto_crosstalk_v2_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_crosstalk_v2_control_proto_goTypes = []any{
	(*ControlMessage)(nil),    // 0: crosstalk.v2.ControlMessage
	(*Hello)(nil),             // 1: crosstalk.v2.Hello
	(*AudioCapability)(nil),   // 2: crosstalk.v2.AudioCapability
	(*Welcome)(nil),           // 3: crosstalk.v2.Welcome
	(*MixUpdate)(nil),         // 4: crosstalk.v2.MixUpdate
	(*RestartCommand)(nil),    // 5: crosstalk.v2.RestartCommand
	(*SessionAssignment)(nil), // 6: crosstalk.v2.SessionAssignment
	(*SourceStatus)(nil),      // 7: crosstalk.v2.SourceStatus
	(*LogEntry)(nil),          // 8: crosstalk.v2.LogEntry
	(*PingPong)(nil),          // 9: crosstalk.v2.PingPong
	nil,                       // 10: crosstalk.v2.LogEntry.FieldsEntry
}
var file_proto_crosstalk_v2_control_proto_depIdxs = []int32{
	1,  // 0: crosstalk.v2.ControlMessage.hello:type_name -> crosstalk.v2.Hello
	7,  // 1: crosstalk.v2.ControlMessage.source_status:type_name -> crosstalk.v2.SourceStatus
	3,  // 2: crosstalk.v2.ControlMessage.welcome:type_name -> crosstalk.v2.Welcome
	4,  // 3: crosstalk.v2.ControlMessage.mix_update:type_name -> crosstalk.v2.MixUpdate
	5,  // 4: crosstalk.v2.ControlMessage.restart:type_name -> crosstalk.v2.RestartCommand
	6,  // 5: crosstalk.v2.ControlMessage.session_assignment:type_name -> crosstalk.v2.SessionAssignment
	8,  // 6: crosstalk.v2.ControlMessage.log_entry:type_name -> crosstalk.v2.LogEntry
	9,  // 7: crosstalk.v2.ControlMessage.ping:type_name -> crosstalk.v2.PingPong
	2,  // 8: crosstalk.v2.Hello.capabilities:type_name -> crosstalk.v2.AudioCapability
	10, // 9: crosstalk.v2.LogEntry.fields:type_name -> crosstalk.v2.LogEntry.FieldsEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_crosstalk_v2_control_proto_init() }
func file_proto_crosstalk_v2_control_proto_init() {
	if File_proto_crosstalk_v2_control_proto != nil {
		return
	}
	file_proto_crosstalk_v2_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_Hello)(nil),
		(*ControlMessage_SourceStatus)(nil),
		(*ControlMessage_Welcome)(nil),
		(*ControlMessage_MixUpdate)(nil),
		(*ControlMessage_Restart)(nil),
		(*ControlMessage_SessionAssignment)(nil),
		(*ControlMessage_LogEntry)(nil),
		(*ControlMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crosstalk_v2_control_proto_rawDesc), len(file_proto_crosstalk_v2_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_crosstalk_v2_control_proto_goTypes,
		DependencyIndexes: file_proto_crosstalk_v2_control_proto_depIdxs,
		MessageInfos:      file_proto_crosstalk_v2_control_proto_msgTypes,
	}.Build()
	File_proto_crosstalk_v2_control_proto = out.File
	file_proto_crosstalk_v2_control_proto_goTypes = nil
	file_proto_crosstalk_v2_control_proto_depIdxs = nil
}
