package http

import (
	"encoding/json"
	"net/http"
	"time"

	crosstalk "github.com/aleksclark/crosstalk/server"
	"github.com/swaggest/openapi-go"
	"github.com/swaggest/openapi-go/openapi31"
)

const securitySchemeName = "bearerAuth"

// --- Request/response types for OpenAPI reflection ---
//
// These types are the single source of truth for the REST API wire format.
// The OpenAPI spec is generated by reflecting on them at init time.
// The TypeScript client is generated from the OpenAPI spec.
//
// Handler code in handler.go uses these same types for JSON encoding/decoding,
// ensuring the spec always matches the implementation.

// pathID is used for endpoints that take an {id} path parameter.
type pathID struct {
	ID string `path:"id" json:"-"`
}

// --- Auth types ---

type loginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type loginResponse struct {
	Token string       `json:"token"`
	User  userResponse `json:"user"`
}

// --- User types (already declared in handler.go, re-used here via alias) ---
// userResponse is declared in handler.go.

type createUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type updateUserRequest struct {
	Username *string `json:"username,omitempty"`
}

// --- Token types (already declared in handler.go, re-used here) ---
// tokenResponse and tokenCreateResponse are declared in handler.go.

type createTokenRequest struct {
	Name string `json:"name"`
}

// --- Template types (already declared in handler.go, re-used here) ---
// templateRequest and templateResponse are declared in handler.go.

// --- Session types ---

type createSessionRequest struct {
	TemplateID string `json:"template_id"`
	Name       string `json:"name"`
}

// sessionResponseOAPI mirrors sessionResponse for OpenAPI reflection.
// We need a separate type because sessionResponse uses crosstalk.SessionStatus
// which doesn't have the enum tag, and we need to document the recording field.
type sessionResponseOAPI struct {
	ID         string                   `json:"id"`
	TemplateID string                   `json:"template_id"`
	Name       string                   `json:"name"`
	Status     string                   `json:"status" enum:"waiting,active,ended"`
	CreatedAt  time.Time                `json:"created_at"`
	EndedAt    *time.Time               `json:"ended_at,omitempty"`
	Recording  *crosstalk.RecordingInfo  `json:"recording,omitempty"`
}

// --- WebRTC token ---

type webrtcTokenResponse struct {
	Token  string `json:"token"`
	Note   string `json:"note"`
	UserID string `json:"user_id"`
}

// --- Error envelope ---
// errorEnvelope and errorBody are declared in handler.go.

// --- Session status query filter ---

type listSessionsQuery struct {
	Status string `query:"status" enum:"waiting,active,ended" description:"Filter by session status"`
}

// buildOpenAPISpec constructs an OpenAPI 3.1 spec by reflecting on the
// request/response Go types used by the handlers. This guarantees the spec
// matches the implementation.
func buildOpenAPISpec() *openapi31.Spec {
	r := openapi31.NewReflector()
	r.Spec.Info.WithTitle("CrossTalk API").WithVersion("0.1.0")

	r.SpecEns().SetHTTPBearerTokenSecurity(securitySchemeName, "", "API token (ct_ prefixed)")

	must := func(err error) {
		if err != nil {
			panic("openapi spec build: " + err.Error())
		}
	}

	// --- Auth ---

	op, _ := r.NewOperationContext(http.MethodPost, "/api/auth/login")
	op.SetSummary("Authenticate with username and password")
	op.SetID("login")
	op.SetTags("auth")
	op.AddReqStructure(new(loginRequest))
	op.AddRespStructure(new(loginResponse))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusUnauthorized))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodPost, "/api/auth/logout")
	op.SetSummary("Revoke the current API token")
	op.SetID("logout")
	op.SetTags("auth")
	op.AddSecurity(securitySchemeName)
	op.AddRespStructure(nil, openapi.WithHTTPStatus(http.StatusNoContent))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodPost, "/api/webrtc/token")
	op.SetSummary("Get WebRTC signaling connection info")
	op.SetID("getWebRTCToken")
	op.SetTags("auth")
	op.AddSecurity(securitySchemeName)
	op.AddRespStructure(new(webrtcTokenResponse))
	must(r.AddOperation(op))

	// --- Users ---

	op, _ = r.NewOperationContext(http.MethodGet, "/api/users")
	op.SetSummary("List all users")
	op.SetID("listUsers")
	op.SetTags("users")
	op.AddSecurity(securitySchemeName)
	op.AddRespStructure(new([]userResponse))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodPost, "/api/users")
	op.SetSummary("Create a new user")
	op.SetID("createUser")
	op.SetTags("users")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(createUserRequest))
	op.AddRespStructure(new(userResponse), openapi.WithHTTPStatus(http.StatusCreated))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodPatch, "/api/users/{id}")
	op.SetSummary("Update a user")
	op.SetID("updateUser")
	op.SetTags("users")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(updateUserRequest), openapi.WithContentType("application/json"))
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(new(userResponse))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodDelete, "/api/users/{id}")
	op.SetSummary("Delete a user")
	op.SetID("deleteUser")
	op.SetTags("users")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(nil, openapi.WithHTTPStatus(http.StatusNoContent))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	// --- Tokens ---

	op, _ = r.NewOperationContext(http.MethodGet, "/api/tokens")
	op.SetSummary("List all API tokens")
	op.SetID("listTokens")
	op.SetTags("tokens")
	op.AddSecurity(securitySchemeName)
	op.AddRespStructure(new([]tokenResponse))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodPost, "/api/tokens")
	op.SetSummary("Create a new API token")
	op.SetID("createToken")
	op.SetTags("tokens")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(createTokenRequest))
	op.AddRespStructure(new(tokenCreateResponse), openapi.WithHTTPStatus(http.StatusCreated))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodDelete, "/api/tokens/{id}")
	op.SetSummary("Revoke an API token")
	op.SetID("deleteToken")
	op.SetTags("tokens")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(nil, openapi.WithHTTPStatus(http.StatusNoContent))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	// --- Templates ---

	op, _ = r.NewOperationContext(http.MethodGet, "/api/templates")
	op.SetSummary("List all session templates")
	op.SetID("listTemplates")
	op.SetTags("templates")
	op.AddSecurity(securitySchemeName)
	op.AddRespStructure(new([]templateResponse))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodPost, "/api/templates")
	op.SetSummary("Create a session template")
	op.SetID("createTemplate")
	op.SetTags("templates")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(templateRequest))
	op.AddRespStructure(new(templateResponse), openapi.WithHTTPStatus(http.StatusCreated))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusBadRequest))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodGet, "/api/templates/{id}")
	op.SetSummary("Get a session template by ID")
	op.SetID("getTemplate")
	op.SetTags("templates")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(new(templateResponse))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodPut, "/api/templates/{id}")
	op.SetSummary("Update a session template")
	op.SetID("updateTemplate")
	op.SetTags("templates")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(templateRequest), openapi.WithContentType("application/json"))
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(new(templateResponse))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodDelete, "/api/templates/{id}")
	op.SetSummary("Delete a session template")
	op.SetID("deleteTemplate")
	op.SetTags("templates")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(nil, openapi.WithHTTPStatus(http.StatusNoContent))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	// --- Sessions ---

	op, _ = r.NewOperationContext(http.MethodGet, "/api/sessions")
	op.SetSummary("List all sessions")
	op.SetID("listSessions")
	op.SetTags("sessions")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(listSessionsQuery))
	op.AddRespStructure(new([]sessionResponseOAPI))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodPost, "/api/sessions")
	op.SetSummary("Create a new session")
	op.SetID("createSession")
	op.SetTags("sessions")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(createSessionRequest))
	op.AddRespStructure(new(sessionResponseOAPI), openapi.WithHTTPStatus(http.StatusCreated))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusBadRequest))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodGet, "/api/sessions/{id}")
	op.SetSummary("Get session detail")
	op.SetID("getSession")
	op.SetTags("sessions")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(new(sessionResponseOAPI))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodDelete, "/api/sessions/{id}")
	op.SetSummary("End a session")
	op.SetID("endSession")
	op.SetTags("sessions")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(nil, openapi.WithHTTPStatus(http.StatusNoContent))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	// --- Clients (stubs) ---

	op, _ = r.NewOperationContext(http.MethodGet, "/api/clients")
	op.SetSummary("List all connected clients")
	op.SetID("listClients")
	op.SetTags("clients")
	op.AddSecurity(securitySchemeName)
	op.AddRespStructure(new([]struct{}))
	must(r.AddOperation(op))

	op, _ = r.NewOperationContext(http.MethodGet, "/api/clients/{id}")
	op.SetSummary("Get client detail")
	op.SetID("getClient")
	op.SetTags("clients")
	op.AddSecurity(securitySchemeName)
	op.AddReqStructure(new(pathID))
	op.AddRespStructure(new(errorEnvelope), openapi.WithHTTPStatus(http.StatusNotFound))
	must(r.AddOperation(op))

	// --- Meta ---

	op, _ = r.NewOperationContext(http.MethodGet, "/api/openapi.json")
	op.SetSummary("Get the OpenAPI specification")
	op.SetID("getOpenAPISpec")
	op.SetTags("meta")
	op.AddSecurity(securitySchemeName)
	op.AddRespStructure(new(json.RawMessage))
	must(r.AddOperation(op))

	return r.Spec
}

// openapiJSON is the serialized OpenAPI spec, built once at init.
var openapiJSON []byte

func init() {
	openapiJSON = OpenAPISpecJSON()
}

// OpenAPISpecJSON returns the OpenAPI 3.1 specification as serialized JSON.
// Called at init time for the handler, and externally by the codegen tool.
func OpenAPISpecJSON() []byte {
	spec := buildOpenAPISpec()
	b, err := spec.MarshalJSON()
	if err != nil {
		panic("failed to marshal openapi spec: " + err.Error())
	}
	return b
}
