#!/usr/bin/env bash
# seed-session.sh — Create session/channels/translator assignment via public APIs.
#
# Never prints passwords or tokens. Writes a redacted seed summary JSON to
# SEED_OUT (default: ./seed-summary.json) containing only non-secret ids/names.
#
# Required env:
#   CROSSTALK_BASE_URL
#   CROSSTALK_ADMIN_PASSWORD   (username defaults to admin)
# Optional:
#   CROSSTALK_ADMIN_USER
#   CROSSTALK_TRANSLATOR_USER / CROSSTALK_TRANSLATOR_PASSWORD
#   CROSSTALK_SESSION_NAME
#   SEED_OUT / SEED_ENV_OUT
set -euo pipefail

BASE_URL="${CROSSTALK_BASE_URL:?CROSSTALK_BASE_URL required}"
BASE_URL="${BASE_URL%/}"
ADMIN_USER="${CROSSTALK_ADMIN_USER:-admin}"
ADMIN_PASS="${CROSSTALK_ADMIN_PASSWORD:?CROSSTALK_ADMIN_PASSWORD required}"
TR_USER="${CROSSTALK_TRANSLATOR_USER:-android_tr_$(date +%s)}"
TR_PASS="${CROSSTALK_TRANSLATOR_PASSWORD:-}"
if [[ -z "$TR_PASS" ]]; then
  TR_PASS="$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))')"
fi
SESSION_NAME="${CROSSTALK_SESSION_NAME:-Sunday Spanish}"
SEED_OUT="${SEED_OUT:-./seed-summary.json}"
ENV_OUT="${SEED_ENV_OUT:-./seed.env}"

export BASE_URL ADMIN_USER ADMIN_PASS TR_USER TR_PASS SESSION_NAME SEED_OUT ENV_OUT

echo "==> Seeding CrossTalk session via public APIs (credentials not echoed)"

python3 - <<'PY'
import json, os, sys, urllib.request, urllib.error

base = os.environ["BASE_URL"].rstrip("/")
admin_user = os.environ["ADMIN_USER"]
admin_pass = os.environ["ADMIN_PASS"]
tr_user = os.environ["TR_USER"]
tr_pass = os.environ["TR_PASS"]
session_name = os.environ["SESSION_NAME"]
seed_out = os.environ["SEED_OUT"]
env_out = os.environ["ENV_OUT"]

def req(method, path, body=None, token=None):
    data = None
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    if body is not None:
        data = json.dumps(body).encode("utf-8")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    r = urllib.request.Request(base + path, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(r, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as e:
        err = e.read().decode("utf-8", errors="replace")
        # Never print request body (may contain passwords).
        print(f"HTTP {e.code} {method} {path}", file=sys.stderr)
        # Avoid dumping tokens if server echoed them.
        print(err[:500], file=sys.stderr)
        raise SystemExit(1)

login = req("POST", "/api/auth/login", {"username": admin_user, "password": admin_pass})
admin_token = login["access_token"]

session = req("POST", "/api/sessions", {
    "name": session_name,
    "description": "Android golden seed",
}, token=admin_token)
session_id = session["id"]

feed = req("POST", f"/api/sessions/{session_id}/channels", {
    "name": "Floor Feed", "type": "feed",
}, token=admin_token)
bcast = req("POST", f"/api/sessions/{session_id}/channels", {
    "name": "English Broadcast", "type": "broadcast",
}, token=admin_token)

tr = req("POST", "/api/translators", {
    "username": tr_user, "password": tr_pass,
}, token=admin_token)
tr_id = tr["id"]

req("PUT", f"/api/translators/{tr_id}/sessions", {
    "session_ids": [session_id],
}, token=admin_token)

abc = req("POST", "/api/abcs", {"name": "android-golden-floor"}, token=admin_token)
abc_id = abc["id"]
abc_token = abc["token"]
req("PUT", f"/api/abcs/{abc_id}", {
    "name": "android-golden-floor",
    "session_id": session_id,
}, token=admin_token)

burl = req("GET", f"/api/sessions/{session_id}/broadcast-url", token=admin_token)
bcast_token = burl["broadcast_token"]

os.makedirs(os.path.dirname(os.path.abspath(env_out)) or ".", exist_ok=True)
with open(env_out, "w") as f:
    os.chmod(env_out, 0o600)
    f.write("# Generated by seed-session.sh — contains secrets. Do not commit.\n")
    f.write(f"export CROSSTALK_BASE_URL={base}\n")
    f.write(f"export CROSSTALK_SESSION_ID={session_id}\n")
    f.write(f"export CROSSTALK_SESSION_NAME={session_name!r}\n".replace("'", '"') if False else "")
    # session name may contain spaces — quote safely
    def shquote(s: str) -> str:
        return "'" + s.replace("'", "'\"'\"'") + "'"
    f.seek(0)
    f.truncate()
    f.write("# Generated by seed-session.sh — contains secrets. Do not commit.\n")
    for k, v in [
        ("CROSSTALK_BASE_URL", base),
        ("CROSSTALK_SESSION_ID", session_id),
        ("CROSSTALK_SESSION_NAME", session_name),
        ("CROSSTALK_FEED_ID", feed["id"]),
        ("CROSSTALK_BROADCAST_ID", bcast["id"]),
        ("CROSSTALK_TRANSLATOR_USER", tr_user),
        ("CROSSTALK_TRANSLATOR_PASSWORD", tr_pass),
        ("CROSSTALK_ABC_ID", abc_id),
        ("CROSSTALK_ABC_TOKEN", abc_token),
        ("CROSSTALK_BROADCAST_TOKEN", bcast_token),
    ]:
        f.write(f"export {k}={shquote(v)}\n")

with open(seed_out, "w") as f:
    json.dump({
        "base_url": base,
        "session_id": session_id,
        "session_name": session_name,
        "feed_id": feed["id"],
        "feed_name": "Floor Feed",
        "broadcast_id": bcast["id"],
        "broadcast_name": "English Broadcast",
        "translator_id": tr_id,
        "translator_user": tr_user,
        "abc_id": abc_id,
        "secrets": "omitted",
    }, f, indent=2)
    f.write("\n")

print(f"==> Seed complete (summary: {seed_out}; secrets env: {env_out})")
print(f"    session_id={session_id} translator_user={tr_user}")
PY
